services:
  db:
    image: postgres:15
    container_name: fundwarden_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: fundwarden_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fundwarden_app
    env_file:
      - .env
    image: fundwarden_docker_app:latest # <--- ADD THIS LINE
    depends_on:
      - db # Tells Docker to start the DB first
    ports:
      - "5000:5000"
    environment:
      # --- Database Configuration ---
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:${DB_PASSWORD}@db:5432/fundwarden_db
      # Don't use @localhost above. Keep @localhost for python run.py and keep @db for Production using Docker.

      # --- Security ---
      - SECRET_KEY=${SECRET_KEY}
      # --- Mail Configuration ---
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${APP_EMAIL_PASSWORD}

      # --- Flask Settings ---
      - FLASK_DEBUG=1
      - FLASK_APP=run.py # This tells Flask: "Open app.py and run create_app()"

    # This allows the container to resolve 'host.docker.internal'
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
