services:
  db:
    image: postgres:15
    container_name: fundwarden_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: fundwarden_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fundwarden_app
    env_file:
      - .env # This loads everything as a backup
    image: fundwarden_docker_app:latest
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      # We MAP them here so Docker explicitly injects them from your .env
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:${DB_PASSWORD}@db:5432/fundwarden_db
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${APP_EMAIL_PASSWORD}
      - FLASK_DEBUG=1
      - FLASK_APP=run.py

    # This allows the container to resolve 'host.docker.internal'
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
